# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GPSStyle' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GPSStyle
  pod 'SwiftLint'
  pod 'PinLayout'
  pod 'SwiftGen', '~> 6.0'

  #UI
  pod 'SnapKit'

  # Api
  pod 'Firebase/Auth'
  pod 'Firebase/Core'

  target 'GPSStyleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GPSStyleUITests' do
    # Pods for testing
  end

end
